# Generated by Django 3.2.3 on 2021-05-23 21:58

from django.db import migrations, models
import django.db.models.deletion
import fictional.infra.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', fictional.infra.fields.AddressField(max_length=100)),
                ('phone', fictional.infra.fields.PhoneField(max_length=20)),
                ('region', fictional.infra.fields.RegionField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vehicles.model')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales.office')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
