# Generated by Django 3.2.3 on 2021-05-25 00:08

from django.db import migrations, models
import django.db.models.deletion
import fictional.infra.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20210523_2200'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=fictional.infra.helpers.dt_now),
        ),
        migrations.AlterField(
            model_name='sale',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.model'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.office'),
        ),
    ]
