# Generated by Django 3.2.3 on 2021-05-23 02:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclepart',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name=uuid.uuid4),
        ),
    ]
